### PR TITLE
Throw unchecked exception in case of a oneway call on the service side

### PR DESCRIPTION
**Pull request by St3ffn**
Fix regarding issue https://github.com/josesamuel/remoter/issues/4

### CODE REVIEW

**Comment by josesamuel** [comment]
Thanks for the PR, but the submitted changes cannot be merged as such as the exception can't be thrown as such from that method. It needs to be wrapped as a RuntimeException. I can make that change in the next update.

**Comment by St3ffn** [comment]
As you mentioned in https://github.com/josesamuel/remoter/issues/4 this issue will be fixed in 1.2.4. Can I expect that version soon? If not I can also offer my help to adapt the PR to wrap it in a RuntimeException. Thanks in advance.

**Comment by josesamuel** [comment]
yes it is already released.. should be available in mavencetral in a couple
of hours

**Comment by St3ffn** [comment]
Perfect. Thanks a lot for your effort.

**Pull request closed without merging**
